### PR TITLE
added where statement to get rid of duplication

### PR DESCRIPTION
**Pull request by KnysakPatryk**
Little fix to get rid of posts duplication

### CODE REVIEW

**Comment by MateuszUrbanowicz** [comment]
:+1:

**Comment by AdrianSkierniewski** [comment]
@KnysakPatryk Did you try to put this where inside a join closure (3 lines above) ? I'd like to see a tests that is recreating that bug, so we can easily test if this solution works.

**Comment by KnysakPatryk** [comment]
@AdrianSkierniewski I didn't but I can try to do it like you said and write the tests as well

**Comment by AdrianSkierniewski** [comment]
@KnysakPatryk it looks good to me :+1: Pls merge it in to master

**Pull request merged**
